language: python
sudo: required
python:
    - "3.4"
install:
    - bash bin/install
script:
    - bash bin/travis
deploy:
  provider: script
  skip_cleanup: true
  script: "bash bin/deploy"
  on:
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_76eb69dddaf6_key -iv $encrypted_76eb69dddaf6_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa